### ISSUE TITLE
Use Static Site Generator

### ISSUE THREAD

**Issue by iqlal** [abarrak/linux-sysops-handbook#10]
Dont Use Gitbook because its close source,
use Static Site Generator for rendering markdown ex. Docusaurus, Nextbook, etc

Thanks

**Comment by abarrak** [comment]
Thanks for the tip @iqlal.
We might consider additional publishing sites, but main gitbook should be there as many people already bookmarked it, and referenced on [hacker news](https://news.ycombinator.com/item?id=30430594)
