### ISSUE TITLE
Is it possible to allow this to be downloaded as a .pdf?

### ISSUE THREAD

**Issue by tangent-man** [abarrak/linux-sysops-handbook#7]
Is it possible to allow this to be downloaded as a .pdf? Then I could print it out or read it on my ebook reader so it is easier to learn...

Thanks

**Comment by abarrak** [comment]
I checked out Gitbook browser print feature, but it doesn't seem to be of good quality.
As an alternative you may print out [the Markdown file](https://raw.githubusercontent.com/abarrak/linux-sysops-handbook/main/README.md) as PDF, using [Typora](https://typora.io/)

Hope this helps 🌹
